CREATE TABLE MetricEntry(
  ID INT AUTO_INCREMENT,
  ENTRY_TIMESTAMP BIGINT NOT NULL,
  ENTRY_DATE VARCHAR(50) NOT NULL,
  ATTRIBUTES LONGTEXT,
  METRIC_GUID VARCHAR(250) NOT NULL
);
ALTER TABLE MetricEntry ADD FOREIGN KEY (METRIC_GUID) REFERENCES Metric(GUID);